package com.norule.musicbot.domain.music;

public enum YoutubeFailureCategory {
    HTTP_FORBIDDEN,
    HTTP_BAD_REQUEST,
    BOT_DETECTED,
    LOGIN_REQUIRED,
    NO_SUPPORTED_AUDIO_STREAM,
    PLAYER_CONFIGURATION_ERROR,
    VIDEO_UNAVAILABLE,
    VIDEO_PRIVATE,
    VIDEO_AGE_RESTRICTED,
    REGION_RESTRICTED,
    SIGNATURE_FAILURE,
    CIPHER_FAILURE,
    CIPHER_REQUIRED_BUT_DISABLED,
    DECODER_FAILURE,
    NETWORK_TIMEOUT,
    NETWORK_IO,
    COMPANION_UNAVAILABLE,
    COMPANION_TIMEOUT,
    COMPANION_AUTH_FAILED,
    COMPANION_BAD_REQUEST,
    COMPANION_STREAM_UNAVAILABLE,
    ALL_CLIENTS_FAILED,
    UNKNOWN
}
